gaicAuto() {
    gAddAutoGeneratedFiles
    g add .
    aicommits
    g push
}

gaic() {
    # We assume that your project is in a directory with the word "bling" in it.
    # If not, either rename your repo or find a more generic solution.
    #
    # Test this assumption by running the following command:
    # $ j bling 
    if [[ $(basename "$(pwd)") == *bling* ]]; then
        gaicAuto
    else
        j bling
        gaicAuto
    fi
}